// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5wvlaHwXb11zDuomr5jLoCcQfDtyfcXY',
    appId: '1:233312165526:web:a63f7d91f54dc03fb16cb7',
    messagingSenderId: '233312165526',
    projectId: 'driverkangsayur',
    authDomain: 'driverkangsayur.firebaseapp.com',
    storageBucket: 'driverkangsayur.appspot.com',
    measurementId: 'G-5MLPH68Z2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkE_1lzKqIZkrrMsuJ0NVNIbDNRGf480',
    appId: '1:233312165526:android:bd7370127becb0bbb16cb7',
    messagingSenderId: '233312165526',
    projectId: 'driverkangsayur',
    storageBucket: 'driverkangsayur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGi3BwwTcDhVnwwY-liacUzkwWmfW6ZKE',
    appId: '1:233312165526:ios:257002f5bc5f591eb16cb7',
    messagingSenderId: '233312165526',
    projectId: 'driverkangsayur',
    storageBucket: 'driverkangsayur.appspot.com',
    iosClientId: '233312165526-1e36b9td50025tbjnjnmg5r7b8bvf00b.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverKangsayur',
  );
}
